#!/usr/bin/env python3

#
# This file is part of LiteX-Boards.
#
# Copyright (c) 2022 Icenowy Zheng <icenowy@aosc.io>
# Copyright (c) 2022 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

from migen import *
from migen.genlib.resetsync import AsyncResetSynchronizer

from litex.gen import *
from litex.soc.interconnect import wishbone
from litex.soc.interconnect.wishbone import SRAM
from litex.build.io import DDROutput

from litex.soc.cores.clock.gowin_gw2a import GW2APLL
from litex.soc.integration.soc_core import *
from litex.soc.integration.soc import SoCRegion
from litex.soc.integration.builder import *
from litex.soc.cores.gpio import GPIOIn
from litex.soc.cores.led import LedChaser, WS2812
from litex.soc.interconnect.csr import *

from litedram.modules import M12L64322A  # FIXME: use the real model number
from litedram.phy import GENSDRPHY

import my_sipeed_tang_nano_20k as sipeed_tang_nano_20k

# CRG ----------------------------------------------------------------------------------------------

class _CRG(LiteXModule):
    def __init__(self, platform, sys_clk_freq):
        self.rst      = Signal()
        self.cd_sys   = ClockDomain()
        self.cd_por   = ClockDomain()

        # Clk
        clk27 = platform.request("clk27")

        # Power on reset
        por_count = Signal(16, reset=2**16-1)
        por_done  = Signal()
        self.comb += self.cd_por.clk.eq(clk27)
        self.comb += por_done.eq(por_count == 0)
        self.sync.por += If(~por_done, por_count.eq(por_count - 1))

        # PLL
        self.pll = pll = GW2APLL(devicename=platform.devicename, device=platform.device)
        self.comb += pll.reset.eq(~por_done)
        pll.register_clkin(clk27, 27e6)
        pll.create_clkout(self.cd_sys, sys_clk_freq)

# BaseSoC ------------------------------------------------------------------------------------------

class BaseSoC(SoCCore):
    def __init__(self, sys_clk_freq=48e6,
        with_led_chaser     = False,
        with_rgb_led        = True,
        with_buttons        = True,
        **kwargs):

        platform = sipeed_tang_nano_20k.Platform(toolchain="gowin")
        
        # add led.v example
        platform.add_source("led.v")
        platform.add_source("led_amaranth.v")
        # end

        # CRG --------------------------------------------------------------------------------------
        self.crg = _CRG(platform, sys_clk_freq)

        # SoCCore ----------------------------------------------------------------------------------
        SoCCore.__init__(self, platform, sys_clk_freq, ident="LiteX SoC on Tang Nano 20K", **kwargs)

        # TODO: XTX SPI Flash

        # SDR SDRAM --------------------------------------------------------------------------------
        if not self.integrated_main_ram_size:
            class SDRAMPads:
                def __init__(self):
                    self.clk   = platform.request("O_sdram_clk")
                    self.cke   = platform.request("O_sdram_cke")
                    self.cs_n  = platform.request("O_sdram_cs_n")
                    self.cas_n = platform.request("O_sdram_cas_n")
                    self.ras_n = platform.request("O_sdram_ras_n")
                    self.we_n  = platform.request("O_sdram_wen_n")
                    self.dm    = platform.request("O_sdram_dqm")
                    self.a     = platform.request("O_sdram_addr")
                    self.ba    = platform.request("O_sdram_ba")
                    self.dq    = platform.request("IO_sdram_dq")
            sdram_pads = SDRAMPads()

            self.specials += DDROutput(0, 1, sdram_pads.clk, ClockSignal("sys"))

            self.sdrphy = GENSDRPHY(sdram_pads, sys_clk_freq)
            self.add_sdram("sdram",
                phy           = self.sdrphy,
                module        = M12L64322A(sys_clk_freq, "1:1"), # FIXME.
                l2_cache_size = 128,
            )

        # Leds -------------------------------------------------------------------------------------
        if with_led_chaser:
            self.leds = LedChaser(
                pads         = platform.request_all("led_n"),
                sys_clk_freq = sys_clk_freq
            )
        # example add led.v verilog code
        # module led(
        #         input       clk,
        #         output      led
        # );
        led    = platform.request("led_n",0)
       # clk27 = self.crg.clk27

        self.specials += Instance("led",

        i_clk    = ClockSignal("sys"),
        o_led = led
        )
        # end example led.v
        # example add led_amaranth.v generated by amaranth
        led1     = platform.request("led_n",1)
       # clk27 = self.crg.clk27

        self.specials += Instance("top", #module name

        i_clk    = ClockSignal("sys"),
        o_led = led1,
        i_rst = ResetSignal("sys")
        )
        #end example led_amaranth.v
        # class example for led with add CSR
        class Led(Module, AutoCSR):
            def __init__(self,buttons):
                self.output = CSRStorage(2,description="Led Output(s) Control.") 
                self.output1 = CSRStorage(24,description="Time") 
                leds_m = []
                for i in range(0,2):
                    leds_m.append(self.output.storage[i])
                
                counter = Signal(24)
                self.sync += counter.eq(counter + 1)
                led_3 = platform.request("led_n",2)
                leds_h =[]
                for i in range(4,6):
                    leds_h.append(platform.request("led_n",i))
               
            # self.leds = platform.request_all("led_n")
                print(leds_h)
                print(leds_m)
                for i in range(2):
                   # self.comb +=leds_h[i].eq(counter[26])
                    self.comb +=leds_h[i].eq(leds_m[i])
                self.sync += [
                      If (counter < self.output1.storage, led_3.eq(0)).Else(
                       led_3.eq(1) # otherwise increment count
                     ),
                    ]
                self.comb+=platform.request("led_n",3).eq(buttons._in.status[0])
                
                

                #mem = Memory(width=32, depth=2)
                #port = mem.get_port()
                
                # Create a wishbone slave interface that wraps the memory object and its port
                #led0_sram = SRAM(mem_or_size=mem, read_only=False, init=None, bus=None)
                
                # Connect the LED's signal to the memory port's data signal
                #self.comb += port.dat_r[0].eq(led)
                
                # Connect the wishbone slave interface to the wishbone bus at address 0x10000000
               # self.bus.add_slave(name="led", slave=led0_sram.bus, region=SoCRegion(
               #         origin = 0x2100_0000,
               #         size   = 1,
               #     ))

       # uncomment for class using        
        
        
        # RGB Led ----------------------------------------------------------------------------------
        if with_rgb_led:
            self.rgb_led = WS2812(
                pad          = platform.request("rgb_led"),
                nleds        = 3,
                sys_clk_freq = sys_clk_freq
            )
            self.bus.add_slave(name="rgb_led", slave=self.rgb_led.bus, region=SoCRegion(
                origin = 0x2000_0000,
                size   = 4,
            ))

          

       
        # Buttons ----------------------------------------------------------------------------------
        #if with_buttons:
        self.buttons = GPIOIn(pads=~platform.request_all("btn"))
        
        self.led = Led(self.buttons)

      
        self.add_csr("led")
        self.add_uartbone(name="serial", baudrate=115200)


# Build --------------------------------------------------------------------------------------------

def main():
    from litex.build.parser import LiteXArgumentParser
    parser = LiteXArgumentParser(platform=sipeed_tang_nano_20k.Platform, description="LiteX SoC on Tang Nano 20K.")
    parser.add_target_argument("--flash",        action="store_true",      help="Flash Bitstream.")
    parser.add_target_argument("--sys-clk-freq", default=48e6, type=float, help="System clock frequency.")
    sdopts = parser.target_group.add_mutually_exclusive_group()
    sdopts.add_argument("--with-spi-sdcard",            action="store_true", help="Enable SPI-mode SDCard support.")
    sdopts.add_argument("--with-sdcard",                action="store_true", help="Enable SDCard support.")
    args = parser.parse_args()

    soc = BaseSoC(
        sys_clk_freq        = args.sys_clk_freq,
        **parser.soc_argdict
    )
    if args.with_spi_sdcard:
        soc.add_spi_sdcard()
    if args.with_sdcard:
        soc.add_sdcard()

    builder = Builder(soc, **parser.builder_argdict)
    if args.build:
        builder.build(**parser.toolchain_argdict)

    if args.load:
        prog = soc.platform.create_programmer()
        prog.load_bitstream(builder.get_bitstream_filename(mode="sram"))

    if args.flash:
        prog = soc.platform.create_programmer()
        prog.flash(0, builder.get_bitstream_filename(mode="flash", ext=".fs"), external=True)

if __name__ == "__main__":
    main()
